baseurl = "https://www.bucksteeg.de/"
languageCode = "en-us"
title = "tricky42"
theme = "hugo-bootstrap-tricky42"
canonifyurls = true
paginate = 3
googleAnalytics = "UA-89935545-1"

[[menu.main]]
    name = "RECOMMENDED"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -90
    identifier = "recommended"
    url = "/page/recommended/"    

[[menu.main]]
    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -80
    identifier = "about-me"
    url = "/page/about-me/"

[[menu.footer]]
    name = "DISCLAIMER"
    weight = -110
    identifier = "disclaimer"
    url = "/page/disclaimer/"

[params.widgets]
  recent_articles = true
  categories = false
  tags = true
  tag_cloud = false
